Redesign amit
bytebeamio/mqttwrk pull request #34
Opened 2020-11-09 05:31 UTC by amrx101

2020-11-09 09:03 UTC, tekjar requested changes

2020-11-09 09:03 UTC, tekjar commented on src/link.rs
> +        indi_sender: Option<Sender<i32>>,
Both the senders can be combined. 

```rust
status_tx: Sender<Status>
```

```
enum Status {
    Progress(usize),
    Histogram(Histogram)
}
```

Also I'm not sure if `Option` is necessary.

2020-11-09 09:03 UTC, tekjar commented on src/bench/connection.rs
> +                            match &self.link.indi_sender.clone(){
This is not correct. Option which has sender is cloned and referenced only to clone it again in Some again. `Sender` implements `Sync + Send`. Why is it being cloned for every `send`?

2020-11-09 09:03 UTC, tekjar commented on src/bench/connection.rs
> +                                    v.clone().send(1).await.unwrap();
Sending progress for every ack doesn't scale for a lot of connections. We should maintain a local counter and periodically send progress.

```rust
loop {
    select! {
        v = eventloop.poll() => { // collect progress }
        _ = periodic_timer => { // send progress }
    }
}
```

2020-11-10 06:11 UTC, amrx101 commented on src/link.rs
> +        indi_sender: Option<Sender<i32>>,
Done

2020-11-10 15:31 UTC, tekjar requested changes

2020-11-10 15:31 UTC, tekjar commented on src/bench/connection.rs
> +                    let mm = match event {
change `let mm` to `let event` or some other better name

2020-11-10 15:31 UTC, tekjar commented on src/bench/connection.rs
> +                                Incoming::PubAck(_pkid) => {
Remove `_` from pkid.

2020-11-10 15:31 UTC, tekjar commented on src/bench/mod.rs
> +    let (c_tx, c_rx) = async_channel::unbounded::<Status>();
Change `c_tx` and `c_rx` to `status_tx`, `status_rx`

2020-11-10 15:31 UTC, tekjar commented on src/bench/mod.rs
> +    let (cc_tx, _) = async_channel::unbounded::<Status>();
If there is no receiver, why is there a channel?

2020-11-10 15:31 UTC, tekjar commented on src/bench/mod.rs
> +    let (cc_tx, _) = async_channel::unbounded::<Status>();
Need a better name than `cc_tx`

2020-11-10 15:31 UTC, tekjar commented on src/bench/mod.rs
> +    let mut r_cnt = 0;
Need a better name than `r_cnt`.

2020-11-10 15:33 UTC, tekjar commented
Left some nits. Also is this tested? Every PR should be tested with atleast a 100 connections.

2020-11-11 03:24 UTC, amrx101 commented
> Left some nits. Also is this tested? Every PR should be tested with atleast a 100 connections.

tested with 100 conns with 10000 messages each con

2020-11-11 05:00 UTC, tekjar approved these changes

2020-11-11 05:00 UTC, merged